### ISSUE TITLE
default editor?

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/Institute-Materials-2017#1]
In the command-line section we may want to tell them how to set up a default shell editor. I use vim, but I'm not certain that that's the best choice for new users who need to get up to speed quickly. What do you both think, both about the choice of an editor and about an online site that might explain how to configure it?

**Comment by ebeshero** [comment]
As a new user who needed to get up to speed quickly on my own about a year ago, I didn't know how to set up an alternative to vim, so I have been learning what commands I need (for dealing with git merge conflicts usually) by looking them up ad hoc on Stack Overflow and elsewhere. It wasn't awful, but if someone took an hour to show me how to work with vim, I think I would have gained a haptic sense of it much more quickly. Since it *is* the default shell editor, when people change systems, if they are dependent on alternative editors they will need to install/configure them. I've never tried to do that--is it worth the trouble? Of better, as I suspect, just to learn vim?

**Comment by djbpitt** [comment]
@ebeshero I think it's definitely better for _you_ to learn vim because you do a lot at the command line and you're willing to make an investment in learning a powerful system even if it takes longer than a simple one. If there were no time pressure, I'd recommend vim to everyone, but since we have a week to get them up to speed, we might want to think about whether our priority should be to teach the better editor or teach the easier one. New users may find nano easier because it displays a menu of command prompts at the bottom of the editing window.

**Comment by ebeshero** [comment]
Having never tried nano, I am eager to give it a shot. I look forward to @narae-pitt 's and @tla 's suggestions! :-)

**Comment by narae-student** [comment]
I use nano alongside emacs and emacs-nox. I never learned or used vim.  For more complex editing tasks, I use Notepad++.


For the workshop purposes, nano will probably be a good choice... it's not like they don't have millions of other things to learn!


Na-Rae



--
Na-Rae Han, Ph.D.
Lecturer, Department of Linguistics
Director, Robert Henderson Language Media Center
--
University of Pittsburgh
G-17 Cathedral of Learning, Pittsburgh, PA 15260
http://www.pitt.edu/~naraehan/
Office: +1 412-624-5939
________________________________

**Comment by djbpitt** [comment]
Updated schedule/week_1/command-line_resources.md to recommend assorted editors, bypassing the shell ones.
