### ISSUE TITLE
tag_words.py code (master and python-xml branches) and Python/XML notebook need review

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/Institute-Materials-2017#18]
@rhdekker Please let me know how the Python/XML notebook looks in Week 1. I've also created an alternative file version of the script, **tag_words.py**, with a `Word` class, in a new **python-xml** branch (not integrated into the notebook). Did I want a static method here? If this is better (or, at least, closer to where we want to be), I can merge it into **master** and adjust the notebook accordingly.

**Comment by rhdekker** [comment]
Review Master:
def get_wordnet_pos(treebank_tag: str) -> str:
This methods uses a lot of if and elif. It could instead be using a dictionary to map from one type to the other. if/elif can be illustrative, but I would not use it in production code.
def extract(input_xml):
the pointer with the current element does not necessary have to be Stack; a variable pointing to the last created element would be good enough, and then instead of popping an element of the Stack we would set the pointer to the parent value of the element that it is currently pointing to.
else if: continue: if that line there for illustrative purposes? It is does not influence the flow of the code in any way.

**Comment by rhdekker** [comment]
Review Python-xml branch:
I like the Word class approach more than the master branch. The only difficult thing might be that it requires a higher level understanding of programming. Like what a Word class is. Difference between class/object, what a static method is and what it does. That the first function that is called in the for loop is actually on the right... so the function calls go from the right to the left. That would need to be explained.

**Comment by rhdekker** [comment]
You could replace the Word class with just a function that creates a "word" element on the tree. The class does not add much.

**Comment by djbpitt** [comment]
Fixed.
