### ISSUE TITLE
White paper tasks, 2018-06

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/Institute-Materials-2017#63]
# Prepare Draft 1
- [x] draft due 06-01 (David, Gabi)
# Review Draft 1
- [x] review by 06-09 (Ronald)
- [x] review by 06-09 (Leif-Jöran)
- [x] review by 06-09 (Elli)
# Revise
- [x] 06-09 – 06-13 (Gabi)
- [x] 06-16 – 06-30 (David

**Comment by rhdekker** [comment]
I reviewed the white paper and in general I think the content is correct. I do have some reservations with the challenges and solutions section. I think that mentioning 4 points (outside of the fact that we had to replace Joris) is quite a lot. When I look at the individual points I recognise point 1 (Software installation) and point 2 (why I am learning this) as the major challenges during the NEH Institute.

Points 3 (Pacing) and 4 (Looking Things Up) to me are general challenges that involve teaching an advanced topic to a diverse group of students. Ergo these challenges happen in every workshop or NEH institute. I view these more as good advice rather than something we that we had to come up with  on the spot. 

I would not so much remove but rather give the last two their own place in the document. 2 major challenges (which we found solutions for) is in my eyes a better description of what actually happened during the workshop.
