### ISSUE TITLE
Python and XML

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/Institute-Materials-2017#7]
The Python units currently say nothing about XML, and getting XML and something like NLTK to play nicely together can be a challenge. If there isn't already a tutorial that does the following (I don't know of one), I can put together an example of how to use Python libraries to read and parse the XML, do something with the text using NLTK, and write out the XML with enriched markup. Perhaps lemmatization or POS tagging?

**Comment by narae-student** [comment]
I wrote a tutorial like that last year. I'll dig it up. I did encounter many problems trying to get NLTK play nicely with XML: I ended up skirting around many issues and bugs, which made me doubt the utility of such tutorial, because once a participant starts straying from the scenario I assembled there were so many pieces not working right. 

Why don't you write up what you have in mind, and perhaps we can synthesize something robust and compact. 

Python Clinic Day 2 probably has some minutes to spare, so this will be good to cover.

**Comment by djbpitt** [comment]
I've started one. Stay tuned ...

**Comment by djbpitt** [comment]
@narae-pitt Done! https://github.com/Pittsburgh-NEH-Institute/Institute-Materials-2017/blob/master/schedule/week_1/Integrating%20XML%20with%20NLTK.ipynb. The line numbers on the code blocks don't survive the generation of static HTML by nbviewer on GitHub, so I'll rewrite the explanation to remove the numbered-line references tomorrow.
